server:
  port: 8081

spring:
  application:
    name: Bootstrap Spring Boot
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${DATABASE_NAME:curses}
    username: ${username}
    password: ${password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    # ${MYSQL_HOST:localhost} : should be mentioned in env variables
    # properties for database connection
  data:
    mongodb:
      host: localhost
      port: 27017
      database: books
  cache:
    type: redis
    host: localhost
    port: 6379
    redis:
      time-to-live: 60000

# spring.kafka.bootstrap-servers specifies the address of your Kafka broker, and spring.kafka.consumer.group-id specifies the consumer group ID for your application
spring.kafka:
  bootstrap-servers: ${KAFKA_BOOTSTRAP_ADDRESS:localhost:9092}
  consumer:
    group-id: ${KAFKA_GROUP_ID:my-group-id}

management:
  endpoints:
    web:
      exposure:
        include: '*'
